# Generated by Django 6.0.5 on 2026-05-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramauthtoken",
            name="short_code",
            field=models.CharField(blank=True, db_index=True, max_length=6),
        ),
    ]
