# Generated by Django 6.0.2 on 2026-06-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_telegramauthtoken_short_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=100)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("language_code", models.CharField(blank=True, max_length=12)),
                ("came_with_token", models.BooleanField(default=False)),
                ("start_count", models.PositiveIntegerField(default=0)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
