# Generated by Django 6.0.2 on 2026-06-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_telegramcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramcontact",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
