# Generated by Django 6.0.2 on 2026-03-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_lesson_slug_alter_skill_slug_and_more'),
        ('learning', '0005_remove_lesson_learning_le_subskil_98add6_idx_and_more'),
    ]

    operations = [
    ]
