# Generated by Django 6.0.2 on 2026-03-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_merge_20260304_1322'),
        ('learning', '0006_videosession_last_play_position'),
    ]

    operations = [
    ]
