# Generated by Django 6.0.2 on 2026-03-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_course_thumbnail'),
        ('learning', '0007_merge_20260326_2017'),
    ]

    operations = [
    ]
