# Generated by Django 5.2 on 2026-05-11 10:30

import django.db.models.deletion
import learning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_merge_0007_course_thumbnail_0007_merge_20260326_2017"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name (e.g. 'code', 'book-open', 'palette')",
                        max_length=40,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Tailwind-ish accent color name (emerald, amber, sky, rose, violet, slate)",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code",
                    models.CharField(
                        default=learning.models._generate_cert_code,
                        max_length=32,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="avg_rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor_bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(default="O'zbek", max_length=40),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Boshlang'ich"),
                    ("intermediate", "O'rta"),
                    ("advanced", "Yuqori"),
                    ("all", "Hamma uchun"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.TextField(
                blank=True, help_text="Bir qatorga bitta talabni yozing."
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="course",
            name="what_you_learn",
            field=models.TextField(
                blank=True, help_text="Bir qatorga bitta bandni yozing."
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_preview",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="learning.category",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["category", "order"], name="learning_co_categor_89fa33_idx"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="learning.course",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="learning.course",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="learning.course",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("user", "course")},
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(
                fields=["course", "-created_at"], name="learning_co_course__788055_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coursereview",
            unique_together={("user", "course")},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["user", "course"], name="learning_en_user_id_7a8bb5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("user", "course")},
        ),
    ]
