# Generated by Django 5.2 on 2026-05-11 19:01
# Simplification migration: replaces VideoSession/VideoEvent + LessonProgress.watched_seconds
# with a lightweight LessonView (user, lesson, day). Preserves historical activity by
# collapsing each VideoSession into one LessonView per (user, lesson, started_at-date).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_sessions_to_views(apps, schema_editor):
    """Backfill LessonView from VideoSession. Idempotent."""
    VideoSession = apps.get_model("learning", "VideoSession")
    LessonView = apps.get_model("learning", "LessonView")

    # Distinct (user, lesson, day) tuples from existing sessions.
    seen = set()
    for row in VideoSession.objects.values("user_id", "lesson_id", "started_at").iterator():
        if not row["user_id"] or not row["lesson_id"]:
            continue
        day = row["started_at"].date() if row["started_at"] else None
        if day is None:
            continue
        key = (row["user_id"], row["lesson_id"], day)
        if key in seen:
            continue
        seen.add(key)
        LessonView.objects.get_or_create(
            user_id=row["user_id"],
            lesson_id=row["lesson_id"],
            viewed_on=day,
        )


def noop_reverse(apps, schema_editor):
    # We won't reconstruct VideoSession; the data has already been collapsed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_category_certificate_coursereview_enrollment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Create LessonView first so we can write into it.
        migrations.CreateModel(
            name="LessonView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_on", models.DateField()),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="learning.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="lessonview",
            index=models.Index(
                fields=["user", "viewed_on"], name="learning_le_user_id_18b28f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonview",
            index=models.Index(
                fields=["user", "lesson"], name="learning_le_user_id_4560e4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonview",
            unique_together={("user", "lesson", "viewed_on")},
        ),

        # 2. Backfill from VideoSession while it still exists.
        migrations.RunPython(copy_sessions_to_views, noop_reverse),

        # 3. Tear down the old machinery.
        migrations.RemoveField(
            model_name="videosession",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="videosession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lessonprogress",
            name="watched_seconds",
        ),
        migrations.DeleteModel(
            name="VideoEvent",
        ),
        migrations.DeleteModel(
            name="VideoSession",
        ),
    ]
