# Generated by Django 6.0.5 on 2026-05-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_learningpath_learningpathcertificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('article', 'Maqola'), ('quiz', 'Test')], default='video', max_length=10),
        ),
    ]
