# Generated by Django 6.0.2 on 2026-06-08 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
