# Generated by Django 6.0.6 on 2026-06-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0015_alter_coursereview_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizanswer",
            name="selected_choices",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="learning.quizchoice"
            ),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Bitta to'g'ri javobli (radio)"),
                    ("multi_select", "Bir nechta to'g'ri javobli (checkbox)"),
                    ("true_false", "To'g'ri/Noto'g'ri"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
    ]
