from django.urls import path
from . import views

app_name = 'learning'

urlpatterns = [
    path(
        '',
        views.CourseListView.as_view(),
        name='course_list',
    ),
    # NOTE: explicit prefixed paths must come BEFORE the <course_slug> catch-all.
    path(
        'qidiruv/',
        views.SearchView.as_view(),
        name='search',
    ),
    path(
        'sevimlilar/',
        views.wishlist_view,
        name='wishlist',
    ),
    path(
        'mening-kurslarim/',
        views.my_learning,
        name='my_learning',
    ),
    path(
        'reyting/',
        views.leaderboard_view,
        name='leaderboard',
    ),
    path(
        'yonalishlar/',
        views.LearningPathListView.as_view(),
        name='learning_path_list',
    ),
    path(
        'yonalish/<slug:path_slug>/',
        views.LearningPathDetailView.as_view(),
        name='learning_path_detail',
    ),
    path(
        'yonalish/<slug:path_slug>/yozilish/',
        views.enroll_learning_path,
        name='enroll_learning_path',
    ),
    path(
        'yonalish/<slug:path_slug>/sertifikat/',
        views.learning_path_certificate,
        name='learning_path_certificate',
    ),
    path(
        'sertifikat/tekshirish/<slug:code>/',
        views.public_certificate_verify,
        name='public_certificate_verify',
    ),
    path(
        'oqituvchi/<slug:username>/',
        views.InstructorDetailView.as_view(),
        name='instructor_detail',
    ),
    path(
        'kategoriya/<slug:slug>/',
        views.CategoryDetailView.as_view(),
        name='category_detail',
    ),
    path(
        '<slug:course_slug>/',
        views.CourseDetailView.as_view(),
        name='course_detail',
    ),
    path(
        '<slug:course_slug>/yozilish/',
        views.enroll_course,
        name='enroll',
    ),
    path(
        '<slug:course_slug>/sharh/',
        views.submit_review,
        name='submit_review',
    ),
    path(
        '<slug:course_slug>/sertifikat/',
        views.certificate_view,
        name='certificate',
    ),
    path(
        '<slug:course_slug>/sevimli/',
        views.toggle_wishlist,
        name='toggle_wishlist',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/',
        views.ModuleDetailView.as_view(),
        name='module_detail',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/',
        views.LessonDetailView.as_view(),
        name='lesson_detail',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/complete/',
        views.mark_lesson_complete,
        name='mark_complete',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/note/',
        views.save_note,
        name='save_note',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/davom/korildi/',
        views.record_view,
        name='record_view',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/savol/',
        views.ask_question,
        name='ask_question',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/savol/<int:question_id>/javob/',
        views.post_answer,
        name='post_answer',
    ),
    # Video bookmarks
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/xatchop/',
        views.save_bookmark,
        name='save_bookmark',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/xatchop/<int:bookmark_id>/ochirish/',
        views.delete_bookmark,
        name='delete_bookmark',
    ),
    # Quiz system
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/test/<int:quiz_id>/',
        views.quiz_detail,
        name='quiz_detail',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/test/<int:quiz_id>/boshlash/',
        views.start_quiz,
        name='start_quiz',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/test/<int:quiz_id>/urinish/<int:attempt_id>/savol/tekshir/',
        views.check_quiz_answer,
        name='check_quiz_answer',
    ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/test/<int:quiz_id>/urinish/<int:attempt_id>/natija/',
        views.quiz_result,
        name='quiz_result',
    ),
]
